baseurl = "http://laptobbe.com/"
languageCode = "en-us"
title = "Laptobbe"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "Laptobbe"
    github = "Laptobbe"
    linkedin = "laptobbe"
    # Google Analytics API key.
    #ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    #mixpanel_api_key = "Your Mixpanel API key"
    author = "Tobias Sundstrand"
    avatar = "/images/me.png"
    contact = "mailto:tobias@threadsafestudio.com"
    bio = "Consulting developer based in Stockholm. I focus on iOS and API design and implementiation."
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Thoughts from a developer"
